server:
  port: 8011

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: apiCars

management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: "*"
    base-path: "/"

logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG
